name: fmas_app
description: A brief description of your package.
version: 1.0.0

environment:
  sdk: '^3.5.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  provider: ^6.0.5
  flutter_form_builder: ^9.5.0
  form_builder_validators: ^11.0.0
  geolocator: ^14.0.0
  shared_preferences: ^2.2.0
  flutter_secure_storage: ^9.2.4
  url_launcher: ^6.1.10
  google_fonts: ^6.2.1
  intl_phone_field: ^3.1.0
  fluttertoast: ^8.2.2